### ISSUE TITLE
CreateEvent Endpoint

### ISSUE THREAD

**Issue by BoKlassen** [Software-Engineering-Group-9/Back-End-API#13]
- Begin working on this endpoint

- Update event DB table schema to match front-ends fetch request

- update SQL commands related to Event Table

**Comment by MingHaoC** [comment]
the new schema for the event table is:
CREATE TABLE event(
eid VARCHAR2(100) NOT NULL,
title VARCHAR2(40),
color VARCHAR2(7),
duedate VARCHAR2(10),
duetime VARCHAR2(6),
userid VARCHAR2(50),
PRIMARY KEY (eid),
FOREIGN KEY (userid) REFERENCES user(uuid)
);
